### ISSUE TITLE
MongoDb schema refresh failed if system.views are present

### ISSUE THREAD

**Issue by aguarino77** [getredash/redash#2779]
### Issue Summary

When creating a query on a MongoDb data source, schema refresh fails if views are present in the database. Even dbAdmin roles on the user defined in the connection string is not enough to prevent the issue. If the db has no views, collections are shown.

Which is the right way (if any!!!) to define the user role needed to get the schema of the mongodb collections?

### Steps to Reproduce

1. Create the monogdb source, test the connection string
2. Create a query

**Comment by mwvaughn** [comment]
I'm hitting the same issue with `v5.0.0-beta` as well as `v4.0.1`. Have you had any luck?

**Comment by hadifarnoud** [comment]
I have the same issue with mongodb data source

**Comment by arikfr** [comment]
Fixed in #2961.

**Comment by AntonTsaberyaby** [comment]
Hi,

The  same issue is still persists

Version: Redash 5.0.2+b5486

**Comment by jodevsa** [comment]
Hi @AntonTsaberyaby

This fix has not been released yet.
For now, you can pull `redash/query_runner/mongodb.py` from the repo and replace it with your current.

**Comment by AntonTsaberyaby** [comment]
@jodevsa Thanks!

**Comment by trung-dbs** [comment]
> Hi @AntonTsaberyaby
> 
> The fix #2961 has not been released yet. Until the next release is published you can pull `redash/query_runner/mongodb.py` from `master` and replace it with your current.

Hello @jodevsa 
I'm using Redash v10.1 but the error still there
![image](https://github.com/getredash/redash/assets/113173254/3fab4cf2-24f9-42c8-a3f9-30fd496f9a66)
![image](https://github.com/getredash/redash/assets/113173254/1c30c38f-4657-494d-9354-3a7cf07d8dbd)
Is any configuration required?
