### ISSUE TITLE
Internal Server Error when Sorting Dashboards

### ISSUE THREAD

**Issue by gthomson31** [getredash/redash#5897]
### Issue Summary

When trying to sort dashboards via name this instantly causes an internal server error.

### Steps to Reproduce

1. Open Redash and select Dashboards 
2. Try to Sort by name 
3. Raises Internal Server Error

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: redash:10.1.0.b50633
* Browser/OS: Chrome
* How did you install Redash: Docker Compose - AWS

**Comment by gaecoli** [comment]
#5645

**Comment by gthomson31** [comment]
This still occurs for us on latest release ?

**Comment by junnplus** [comment]
> This still occurs for us on latest release ?

I have verified that it has been fixed in the latest code.

**Comment by gthomson31** [comment]
I am on the latest release ?

**Comment by gaecoli** [comment]
> I am on the latest release ?

You now at 10.1.0, this version not fixed this bug. Maybe you should update code.

**Comment by gthomson31** [comment]
What release are you referring too that this is fixed 
Looking at [releases](https://github.com/getredash/redash/releases)  10.1.0 is the latest

**Comment by gaecoli** [comment]
> What release are you referring too that this is fixed Looking at [releases](https://github.com/getredash/redash/releases) 10.1.0 is the latest

master branch fixed.
