### ISSUE TITLE
CSV still a viable DataSource

### ISSUE THREAD

**Issue by sourkidk** [getredash/redash#6082]
### Discussed in https://github.com/getredash/redash/discussions/6078

<div type='discussions-op-text'>

<sup>Originally posted by **sourkidk** June  4, 2023</sup>
I'm hoping to use csv files published to a url as datasource, and I can see in the documentation the syntax for how it should be done.  However, there doesn't seem to be a datasource type that matches this use, and I cannot get the query to execute in other types.  

Here's a link to the doc page. 

[https://redash.io/help/data-sources/querying/csv-excel-files](url)
</div>

**Comment by rutson** [comment]
Just tested using the CSV source and query:


```
url: https://pkgstore.datahub.io/core/country-list/data_csv/data/d7c9d7cfb42cb69f4422dec222dbbaa8/data_csv.csv
```

And it works ok

**Comment by deathvulture** [comment]
There was a problem with excel and csv querys but it should have been fixed with this PR https://github.com/getredash/redash/pull/6439

**Comment by kupletist** [comment]
> There was a problem with excel and csv querys but it should have been fixed with this PR #6439

looks like the problem is still here( - https://images2.imgbox.com/0c/87/DfJfLPGA_o.png 
how can i avoid this error?

**Comment by rutson** [comment]
@kupletist, it looks like your source is of type 'Query results' 
<img width="153" alt="image" src="https://github.com/getredash/redash/assets/14196062/a006106e-fce9-4984-852a-858806359873">

it needs to be of type `CSV`
<img width="79" alt="image" src="https://github.com/getredash/redash/assets/14196062/760fa555-c490-4683-89f9-dc929f5303b9">

**Comment by kupletist** [comment]
Hi Rutson! But i don't have such a data source at self-hosted Redush, unfortunately - https://redash.io/help/data-sources/querying/supported-data-sources

**Comment by rutson** [comment]
Oh, that's odd. Also self hosted (v10.1.0). If I go to `Settings` then `+ New Data Source` I see `CSV` as an option

<img width="428" alt="image" src="https://github.com/getredash/redash/assets/14196062/237196df-89f2-4bbd-9f78-1a50ed6b0746">

**Comment by kupletist** [comment]
Wow, i have an 8.0 version... I think it's time to upgrade. Thanks!

**Comment by kupletist** [comment]
Sorry for my next question: just upgraded, but how to get to Initial Setup screen? Redash throws me only to Login screen, but i need to get to the first screen, with admin setup... (can't login, cause all accounts have been deleted). maybe there is some easy way, with changing .env file, for example...

**Comment by rutson** [comment]
I don't know that I'm afraid, but we're definitely off topic now - maybe try https://github.com/getredash/redash/discussions/ ?

**Comment by deathvulture** [comment]
Did you use this guide? https://redash.io/help/open-source/admin-guide/how-to-upgrade. If you can't make it work try as @rutson said to open a new discussion.
